version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mydatabase
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-spring-boot-app
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:example@mongo-db:27017/mydatabase
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
